### ISSUE TITLE
Just an example

### ISSUE THREAD

**Issue by xeviff** [Akarys42/cloudflare-ddns-docker#2]
Hi!.
Just wanted to do more easy work for people that face this: A command example

```
docker run --name ddns_client --rm \
-e CF_DDNS_DOMAINS="mydomain.cat *.mydomain.cat mail.mydomain.cat" \
-d ghcr.io/akarys42/cloudflare-ddns-docker -k [REDACTED]
```

I tried to translate into a docker-compose without success. Maybe someone wanted to do this next step?
Regards

**Comment by Akarys42** [comment]
Hello @xeviff! Thank you for opening an issue.

This would indeed be a correct way to start the project. I would recommend you to either supply all your parameters using env vars or command line arguments. For example:

```
docker run --name ddns_client --rm \
-e CF_DDNS_DOMAINS="mydomain.cat *.mydomain.cat mail.mydomain.cat" \
-e CF_DDNS_TOKEN="[REDACTED]" \
-d ghcr.io/akarys42/cloudflare-ddns-docker 
```
or
```
docker run --name ddns_client --rm \
-d ghcr.io/akarys42/cloudflare-ddns-docker \
-k [REDACTED] \
mydomain.cat *.mydomain.cat mail.mydomain.cat
```

In a docker-compose, you should be able to a similar thing:
```yaml
version: "3.7"
services:
  cloudflare-ddns:
    image: ghcr.io/akarys42/cloudflare-ddns-docker
    container_name: ddns_client
    enviroment:
      CF_DDNS_DOMAINS: "mydomain.cat *.mydomain.cat mail.mydomain.cat" 
      CF_DDNS_TOKEN: "[REDACTED]" 
```

That said, I 100% agree that this project is lacking proper setup instructions. So here is what I'm thinking:
- [ ] Add the three examples above to the README
- [ ] Rename `docker-compose.yaml` to `dev-docker-compose.yaml`
- [ ] Maybe add an example `docker-compose.yaml` file?

Would you be interested in making those changes?

---

Also it seemed like you passed an actual token in your original comment. I took the liberty to redact it just in case, but if it was valid please do [roll it](https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys#12345681) right now.

**Comment by xeviff** [comment]
Hello @Akarys42  !! Thank you very much for your response.
I apreciate your concern about my token but I changed some characters in order to not provide a real token.

You proposed interesting changes and if I have some free time I'll put them into a pull request.
Regards

**Comment by Akarys42** [comment]
Awesome, thank you!

**Comment by jt196** [comment]
I can see this hasn't been updated for a while, but I thought I'd give some feedback here. I've just set this up using docker compose, and as far as I can see it's working, so thanks for taking the time to write the script.

Here's my working docker-compose file:

```yaml
## Development docker-compose
version: "3.7"
services:
  cloudflare-ddns:
    image: ghcr.io/akarys42/cloudflare-ddns-docker
    container_name: cloudflare-ddns
    environment:
      - CF_DDNS_TOKEN=<my_token>
      - CF_DDNS_DELAY=1 hour
      - CF_DDNS_DOMAINS=<my_domain>.com
``` 

A little feedback here:

1. Some documentation on the delay would be useful, perhaps include in an example. I had to dig around into the utils.py file, and needed to not use quotation marks around the string for it to work!
2. Some user feedback in the logs would also be useful. e.g. "IP Address: 82.22.12.131, updating DNS records!" I don't know if they check if it's the same or not...
3. I'm assuming that wildcard records formatting is something like this: `- CF_DDNS_DOMAINS=*.<my_domain>.com`, this seems to be working correctly and not erroring out.
